banking_lakehouse:
  target: dev
  outputs:
    dev:
      type: trino
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '8081') | int }}"
      user: airflow
      catalog: "{{ env_var('TRINO_CATALOG', 'delta_lake') }}"
      schema: "{{ env_var('TRINO_SCHEMA', 'gold') }}"
      threads: 4
      http_scheme: http

